complexity:
  LongParameterList:
    active: true
    constructorThreshold: 8
    functionThreshold: 8
  TooManyFunctions:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  ReturnCount:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
